<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="87663" started-at="2018-03-30T09:08:53Z" finished-at="2018-03-30T09:10:20Z">
    <groups>
    </groups>
    <test name="Change Password" duration-ms="87663" started-at="2018-03-30T09:08:53Z" finished-at="2018-03-30T09:10:20Z">
      <class name="TestCases.ChangePasswordTest">
        <test-method status="PASS" signature="extentSetup(org.testng.ITestContext)[pri:0, instance:TestCases.ChangePasswordTest@1700915]" name="extentSetup" is-config="true" duration-ms="299" started-at="2018-03-30T14:38:52Z" finished-at="2018-03-30T14:38:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@6dcd5639]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentSetup -->
        <test-method status="PASS" signature="initializeTestBaseSetup(java.lang.reflect.Method)[pri:0, instance:TestCases.ChangePasswordTest@1700915]" name="initializeTestBaseSetup" is-config="true" duration-ms="7210" started-at="2018-03-30T14:38:53Z" finished-at="2018-03-30T14:39:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void TestCases.ChangePasswordTest.verifyChangePasswordWithIncorrectOldPassword()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeTestBaseSetup -->
        <test-method status="FAIL" signature="verifyChangePasswordWithIncorrectOldPassword()[pri:0, instance:TestCases.ChangePasswordTest@1700915]" name="verifyChangePasswordWithIncorrectOldPassword" duration-ms="35546" started-at="2018-03-30T14:39:00Z" finished-at="2018-03-30T14:39:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Incorrect Old password feature is not working expected [Old Password incorrect] but found [Old Password is incorrect]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Incorrect Old password feature is not working expected [Old Password incorrect] but found [Old Password is incorrect]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at TestCases.ChangePasswordTest.verifyChangePasswordWithIncorrectOldPassword(ChangePasswordTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyChangePasswordWithIncorrectOldPassword -->
        <test-method status="PASS" signature="afterEachTestMethod(org.testng.ITestResult)[pri:0, instance:TestCases.ChangePasswordTest@1700915]" name="afterEachTestMethod" is-config="true" duration-ms="15639" started-at="2018-03-30T14:39:39Z" finished-at="2018-03-30T14:39:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyChangePasswordWithIncorrectOldPassword status=FAILURE method=ChangePasswordTest.verifyChangePasswordWithIncorrectOldPassword()[pri:0, instance:TestCases.ChangePasswordTest@1700915] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterEachTestMethod -->
        <test-method status="PASS" signature="generateReport()[pri:0, instance:TestCases.ChangePasswordTest@1700915]" name="generateReport" is-config="true" duration-ms="2675" started-at="2018-03-30T14:40:27Z" finished-at="2018-03-30T14:40:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReport -->
      </class> <!-- TestCases.ChangePasswordTest -->
    </test> <!-- Change Password -->
  </suite> <!-- Suite1 -->
</testng-results>
